version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: ./budget_api/
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  message:
    build: ./message_api/
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"

volumes:
  postgres_data:
